### ISSUE TITLE
Bug in gaussj function

### ISSUE THREAD

**Issue by logicmonkey** [jadecci/numerical_recipes_c#1]
I noticed that A.A_inv != I

Loop end condition should be j<m, not n

https://github.com/jadecci/numerical_recipes_c/blob/21e1bde6752769e503d3d94dfe0c626eeaa9375a/chpt2_gauss_jordan_full_pivot.c#L41

**Comment by jadecci** [comment]
Thanks for spotting the bug! This has been corrected in the commit `d3fab55727c2df0bb205db53ffa2657f2b89dabfz`.
